### ISSUE TITLE
Error after ugrade

### ISSUE THREAD

**Issue by didier-lasnier** [CubikNeRubik/angular-electron-typeorm-starter#13]
Hi,
Your example is great, so I use it to startt my own application.
but I encounter an issue after I upgrade the angular module from 8.0.3 to 8.2.35. I've got an  error when start the app. So i reload your example from your repository and try to update your' app. 
got the same error.
Below the error I've got at 'npm run start' command. 
Have you an idea to solve this issue ?

`[error] ReferenceError: path is not defined
    at Object.getBrowserConfig (/Volumes/Data/ProjetNodes/TestUpdate/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js:62:22)
    at webpack_browser_config_1.generateBrowserWebpackConfigFromContext.wco (/Volumes/Data/ProjetNodes/TestUpdate/node_modules/@angular-devkit/build-angular/src/browser/index.js:55:27)
    at scriptTargets.map.scriptTarget (/Volumes/Data/ProjetNodes/TestUpdate/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:69:26)
    at Array.map (<anonymous>)
    at generateWebpackConfig (/Volumes/Data/ProjetNodes/TestUpdate/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:33:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
`

**Comment by CubikNeRubik** [comment]
Hi @didier-lasnier
Thank you for the issue report

I guess that problem somewhere in the post-install script. You can see that I change file from error log `webpack-configs/browser.js` in `postinstall.js` script.

**Comment by CubikNeRubik** [comment]
@didier-lasnier now issue should be fixed
