### ISSUE TITLE
updating packages to the lastest

### ISSUE THREAD

**Issue by zuoshuluHTC** [CubikNeRubik/angular-electron-typeorm-starter#15]
Hi, I am working on the project using angular and electron. I wanna bring in typeorm for sqlite and ms sql. Does angular-electron-typeorm-starter support current angular 9, electron 8.1.1 and typeorm 0.2.24?

**Comment by CubikNeRubik** [comment]
Hi, @zuoshuluHTC. I am working on the update.

**Comment by zuoshuluHTC** [comment]
Thanks for your reply, you wrote "can not use TypeOrm in browser". I found this angular-electron package under  [https://github.com/maximegris/angular-electron](url) works in browser mode.

**Comment by CubikNeRubik** [comment]
@zuoshuluHTC, sure it is work because of [angular-electron](https://github.com/maximegris/angular-electron) don't use TypeOrm)
Indeed you can use it in browser mode at least I saw samples with IndexDB. But I didn't achieve full compatibility with both electron and browser.

**Comment by cyrilfr** [comment]
Hi @CubikNeRubik, did you manage to make to work with the last TypeORM version (v0.2.30)?.
I've this error at runtime (loader error):

```
App threw an error during load
TypeError: Cannot read property 'indexOf' of undefined
    at isInstalledWithPNPM (/home/cyril/Documents/app/node_modules/app-root-path/lib/resolve.js:30:25)
    at resolve (/home/cyril/Documents/app/node_modules/app-root-path/lib/resolve.js:84:6)
    at module.exports (/home/cyril/Documents/app/node_modules/app-root-path/lib/app-root-path.js:6:20)
    at Object.<anonymous> (/home/cyril/Documents/app/node_modules/app-root-path/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'indexOf' of undefined
    at isInstalledWithPNPM (/home/cyril/Documents/app/node_modules/app-root-path/lib/resolve.js:30:25)
    at resolve (/home/cyril/Documents/app/node_modules/app-root-path/lib/resolve.js:84:6)
    at module.exports (/home/cyril/Documents/app/node_modules/app-root-path/lib/app-root-path.js:6:20)
    at Object.<anonymous> (/home/cyril/Documents/app/node_modules/app-root-path/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
```
