### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by aliabidzaidi** [CubikNeRubik/angular-electron-typeorm-starter#16]
There might be something wrong with my environment, guide me, it fails on this point (logs)

1078 verbose stack Error: sqlite3@4.0.9 install: `node-pre-gyp install --fallback-to-build`
1078 verbose stack Exit status 1
1078 verbose stack     at EventEmitter.<anonymous> (C:\Users\abidzaidi\AppData\Roaming\nvm\v13.9.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
1078 verbose stack     at EventEmitter.emit (events.js:321:20)
1078 verbose stack     at ChildProcess.<anonymous> (C:\Users\abidzaidi\AppData\Roaming\nvm\v13.9.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1078 verbose stack     at ChildProcess.emit (events.js:321:20)
1078 verbose stack     at maybeClose (internal/child_process.js:1026:16)
1078 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
1079 verbose pkgid sqlite3@4.0.9
1080 verbose cwd D:\source\angular\angular-electron-typeorm-starter
1081 verbose Windows_NT 10.0.18362
1082 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
1083 verbose node v13.9.0
1084 verbose npm  v6.13.7
1085 error code ELIFECYCLE
1086 error errno 1
1087 error sqlite3@4.0.9 install: `node-pre-gyp install --fallback-to-build`
1087 error Exit status 1
1088 error Failed at the sqlite3@4.0.9 install script.
1088 error This is probably not a problem with npm. There is likely additional logging output above.
1089 verbose exit [ 1, true ]

**Comment by aliabidzaidi** [comment]
Fixed this issue by installing [v140 toolset](https://devblogs.microsoft.com/cppblog/visual-studio-build-tools-now-include-the-vs2017-and-vs2015-msvc-toolsets/) 
this is needed for sqlite3 on npm install
