### ISSUE TITLE
Possible issue: unnecessary reference to Gnome extension?!?

### ISSUE THREAD

**Issue by tonydiep** [CubikNeRubik/angular-electron-typeorm-starter#8]
I'm not sure if this is an actual issue with this repo or specific to my machine but I haven't seen this error with any other repos on this machine.

* npm run electron:local succeeds but there is a warning that a theme file is missing. 
```
(electron:15902): Gtk-WARNING **: 22:11:35.889: Theme parsing error: gtk.css:1:110: Failed to import: Error opening file /home/tonydiep/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-right.css: No such file or directory
[15902:0714/221138.082757:ERROR:CONSOLE(972)] "TypeError: Cannot read property 'pseudoType' of undefined TypeError: Cannot read property 'pseudoType' of undefined
    at SDK.DOMNode._removeChild (chrome-devtools://devtools/bundled/shell.js:4301:28)
    at SDK.DOMModel._childNodeRemoved (chrome-devtools://devtools/bundled/shell.js:4420:121)
    at SDK.DOMDispatcher.childNodeRemoved (chrome-devtools://devtools/bundled/shell.js:4464:54)
    at Protocol.InspectorBackend._DispatcherPrototype.dispatch (chrome-devtools://devtools/bundled/shell.js:3399:26)
    at Protocol.SessionRouter._onMessage (chrome-devtools://devtools/bundled/shell.js:3355:41)
    at SDK.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/shell.js:3486:17)
    at Common.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:494:23)
    at innerDispatch (chrome-devtools://devtools/bundled/shell.js:972:98)
    at Host.InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/bundled/shell.js:972:1)
    at DevToolsAPIImpl._dispatchOnInspectorFrontendAPI (chrome-devtools://devtools/bundled/devtools_compatibility.js:57:36)", source: chrome-devtools://devtools/bundled/shell.js (972)
```
* I'm not using this particular theme / Gnome extension so something in the repo may be referencing this file?
* I do not get this warning with any other repo
* workaround is to install [https://github.com/hardpixel/unite-shell](https://github.com/hardpixel/unite-shell)

**Comment by AdditionAddict** [comment]
@tonydiep I've had this error with other electron starters as well as this one and I don't thinks it is necessarily the starter's fault unless there is some obscure reason the error occurs. I added a bounty to the following SO question but there was no response:
 
https://stackoverflow.com/questions/56088355/typeerror-with-chrome-devtools
