### ISSUE TITLE
Electron Linux build fails because icons don't exist?

### ISSUE THREAD

**Issue by tonydiep** [CubikNeRubik/angular-electron-typeorm-starter#9]
npm run electron:linux fails with 

⨯ icon directory /home/tonydiep/Projects/angular-electron-typeorm-starter/dist doesn't contain icons

May be related to issue with electron-builder
[https://github.com/electron-userland/electron-builder/issues/2570](https://github.com/electron-userland/electron-builder/issues/2570)

```
  ⨯ icon directory /home/tonydiep/Projects/angular-electron-typeorm-starter/dist doesn't contain icons
github.com/develar/app-builder/pkg/icons.CollectIcons
	/Volumes/data/Documents/app-builder/pkg/icons/collect-icons.go:72
github.com/develar/app-builder/pkg/icons.doConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:194
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337
github.com/develar/app-builder/pkg/icons.doConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:196
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337

Error: /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
From previous event:
    at LinuxPackager.resolveIcon (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/platformPackager.ts:594:101)
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/targets/LinuxTargetHelper.ts:35:35
    at Generator.next (<anonymous>)
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/targets/LinuxTargetHelper.ts:23:36)
    at Lazy.LinuxTargetHelper.iconPromise (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/targets/LinuxTargetHelper.ts:11:54)
    at Lazy.get value [as value] (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/lazy-val/src/main.ts:18:25)
    at LinuxTargetHelper.get icons [as icons] (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/targets/LinuxTargetHelper.ts:19:29)
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:43:19
From previous event:
    at AppImageTarget.build (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:27:44)
    at Function.buildAsyncTargets (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at LinuxPackager.pack (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/home/tonydiep/Projects/angular-electron-typeorm-starter/node_modules/electron-builder/src/cli/cli.ts:49:19)
```

**Comment by CubikNeRubik** [comment]
Hi @tonydiep ,
I don't work with Linux version too much. You can try to use the previos version (it work fine on Linux). Also, give me know if you find any solution to your problem. 
Thanks

**Comment by asif633** [comment]
Hi @tonydiep @CubikNeRubik ,
I have successfully built for Ubuntu. You have to replace favicon.ico with favicon.png. The above error was showing because of favicon.ico.
